Citizen.CreateThread(function()
    print("^2================================================================^0")
    print("^5[kypz_elevator]^2 Başarıyla Yüklendi!^0")
    print("^5[Yazar]^0: Antigravity & Kaypuz")
    print("^5[Sürüm]^0: 1.0.0")
    print("^5[HUD Tasarımı]^2: Premium Metalik Buton Paneli (Web Audio Sentezleyici Aktif)^0")
    print("^2================================================================^0")
end)
